// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Apuestum struct {
	IDApuesta    int32        `json:"id_apuesta"`
	IDUsuario    int32        `json:"id_usuario"`
	IDGranPremio string       `json:"id_gran_premio"`
	FechaCarrera time.Time    `json:"fecha_carrera"`
	Prediccion   []int32      `json:"prediccion"`
	FechaApuesta sql.NullTime `json:"fecha_apuesta"`
}

type Escuderium struct {
	IDEscuderia          string        `json:"id_escuderia"`
	PuntosTemporada      sql.NullInt32 `json:"puntos_temporada"`
	TitulosConstructores sql.NullInt32 `json:"titulos_constructores"`
	FechaFundacion       sql.NullTime  `json:"fecha_fundacion"`
	TeamPrincipal        string        `json:"team_principal"`
}

type GranPremio struct {
	IDGranPremio    string         `json:"id_gran_premio"`
	Pais            string         `json:"pais"`
	LongitudKm      sql.NullString `json:"longitud_km"`
	CantidadVueltas sql.NullInt32  `json:"cantidad_vueltas"`
	IDUltimoGanador sql.NullInt32  `json:"id_ultimo_ganador"`
}

type GranPremioHistorico struct {
	IDGranPremio     string    `json:"id_gran_premio"`
	FechaCarrera     time.Time `json:"fecha_carrera"`
	ResultadoCarrera []int32   `json:"resultado_carrera"`
}

type Piloto struct {
	IDPiloto        int32          `json:"id_piloto"`
	IDEscuderia     sql.NullString `json:"id_escuderia"`
	PuntosTemporada sql.NullInt32  `json:"puntos_temporada"`
}

type PilotoHistorico struct {
	IDPiloto        int32         `json:"id_piloto"`
	Nombre          string        `json:"nombre"`
	Pais            string        `json:"pais"`
	FechaNacimiento time.Time     `json:"fecha_nacimiento"`
	TitulosGanados  sql.NullInt32 `json:"titulos_ganados"`
}

type Usuario struct {
	IDUsuario      int32         `json:"id_usuario"`
	NombreUsuario  string        `json:"nombre_usuario"`
	ContrasenaHash string        `json:"contrasena_hash"`
	PuntosGanados  sql.NullInt32 `json:"puntos_ganados"`
}
