// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const borrarApuesta = `-- name: BorrarApuesta :exec
DELETE FROM apuesta
WHERE id_apuesta = $1
`

// Eliminar una apuesta
func (q *Queries) BorrarApuesta(ctx context.Context, idApuesta int32) error {
	_, err := q.db.ExecContext(ctx, borrarApuesta, idApuesta)
	return err
}

const crearApuesta = `-- name: CrearApuesta :one

INSERT INTO apuesta (
    id_usuario,
    id_gran_premio,
    fecha_carrera,
    prediccion
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id_apuesta,
    id_usuario,
    id_gran_premio,
    fecha_carrera,
    prediccion,
    fecha_apuesta
`

type CrearApuestaParams struct {
	IDUsuario    int32     `json:"id_usuario"`
	IDGranPremio string    `json:"id_gran_premio"`
	FechaCarrera time.Time `json:"fecha_carrera"`
	Prediccion   []int32   `json:"prediccion"`
}

// ==========================================
// APUESTAS
// ==========================================
// Crear una apuesta vinculada a un evento de carrera específico
func (q *Queries) CrearApuesta(ctx context.Context, arg CrearApuestaParams) (Apuestum, error) {
	row := q.db.QueryRowContext(ctx, crearApuesta,
		arg.IDUsuario,
		arg.IDGranPremio,
		arg.FechaCarrera,
		pq.Array(arg.Prediccion),
	)
	var i Apuestum
	err := row.Scan(
		&i.IDApuesta,
		&i.IDUsuario,
		&i.IDGranPremio,
		&i.FechaCarrera,
		pq.Array(&i.Prediccion),
		&i.FechaApuesta,
	)
	return i, err
}

const crearEscuderia = `-- name: CrearEscuderia :one
INSERT INTO escuderia (
    id_escuderia,
    puntos_temporada,
    titulos_constructores,
    fecha_fundacion,
    team_principal
) VALUES (
    $1,
    COALESCE($2, 0),
    COALESCE($3, 0),
    $4,
    $5
)
RETURNING id_escuderia, puntos_temporada, titulos_constructores, fecha_fundacion, team_principal
`

type CrearEscuderiaParams struct {
	IDEscuderia    string       `json:"id_escuderia"`
	Column2        interface{}  `json:"column_2"`
	Column3        interface{}  `json:"column_3"`
	FechaFundacion sql.NullTime `json:"fecha_fundacion"`
	TeamPrincipal  string       `json:"team_principal"`
}

// Registrar una nueva escudería
func (q *Queries) CrearEscuderia(ctx context.Context, arg CrearEscuderiaParams) (Escuderium, error) {
	row := q.db.QueryRowContext(ctx, crearEscuderia,
		arg.IDEscuderia,
		arg.Column2,
		arg.Column3,
		arg.FechaFundacion,
		arg.TeamPrincipal,
	)
	var i Escuderium
	err := row.Scan(
		&i.IDEscuderia,
		&i.PuntosTemporada,
		&i.TitulosConstructores,
		&i.FechaFundacion,
		&i.TeamPrincipal,
	)
	return i, err
}

const crearGranPremio = `-- name: CrearGranPremio :one

INSERT INTO gran_premio (
    id_gran_premio,
    pais,
    longitud_km,
    cantidad_vueltas,
    id_ultimo_ganador
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id_gran_premio, pais, longitud_km, cantidad_vueltas, id_ultimo_ganador
`

type CrearGranPremioParams struct {
	IDGranPremio    string         `json:"id_gran_premio"`
	Pais            string         `json:"pais"`
	LongitudKm      sql.NullString `json:"longitud_km"`
	CantidadVueltas sql.NullInt32  `json:"cantidad_vueltas"`
	IDUltimoGanador sql.NullInt32  `json:"id_ultimo_ganador"`
}

// ==========================================
// GRANDES PREMIOS / CIRCUITOS
// ==========================================
// Registrar un circuito en el catálogo histórico
func (q *Queries) CrearGranPremio(ctx context.Context, arg CrearGranPremioParams) (GranPremio, error) {
	row := q.db.QueryRowContext(ctx, crearGranPremio,
		arg.IDGranPremio,
		arg.Pais,
		arg.LongitudKm,
		arg.CantidadVueltas,
		arg.IDUltimoGanador,
	)
	var i GranPremio
	err := row.Scan(
		&i.IDGranPremio,
		&i.Pais,
		&i.LongitudKm,
		&i.CantidadVueltas,
		&i.IDUltimoGanador,
	)
	return i, err
}

const crearGranPremioHistorico = `-- name: CrearGranPremioHistorico :one

INSERT INTO gran_premio_historico (
    id_gran_premio,
    fecha_carrera,
    resultado_carrera
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id_gran_premio, fecha_carrera, resultado_carrera
`

type CrearGranPremioHistoricoParams struct {
	IDGranPremio     string    `json:"id_gran_premio"`
	FechaCarrera     time.Time `json:"fecha_carrera"`
	ResultadoCarrera []int32   `json:"resultado_carrera"`
}

// ==========================================
// EDICIONES / EVENTOS DE GRANDES PREMIOS
// ==========================================
// Programar una fecha/carrera concreta de un Gran Premio
func (q *Queries) CrearGranPremioHistorico(ctx context.Context, arg CrearGranPremioHistoricoParams) (GranPremioHistorico, error) {
	row := q.db.QueryRowContext(ctx, crearGranPremioHistorico, arg.IDGranPremio, arg.FechaCarrera, pq.Array(arg.ResultadoCarrera))
	var i GranPremioHistorico
	err := row.Scan(&i.IDGranPremio, &i.FechaCarrera, pq.Array(&i.ResultadoCarrera))
	return i, err
}

const crearPilotoHistorico = `-- name: CrearPilotoHistorico :one

INSERT INTO piloto_historico (
    id_piloto,
    nombre,
    pais,
    fecha_nacimiento,
    titulos_ganados
) VALUES (
    $1,
    $2,
    $3,
    $4,
    COALESCE($5, 0)
)
RETURNING id_piloto, nombre, pais, fecha_nacimiento, titulos_ganados
`

type CrearPilotoHistoricoParams struct {
	IDPiloto        int32       `json:"id_piloto"`
	Nombre          string      `json:"nombre"`
	Pais            string      `json:"pais"`
	FechaNacimiento time.Time   `json:"fecha_nacimiento"`
	Column5         interface{} `json:"column_5"`
}

// ==========================================
// PILOTOS HISTÓRICOS
// ==========================================
// Registrar datos biográficos/históricos de un piloto
func (q *Queries) CrearPilotoHistorico(ctx context.Context, arg CrearPilotoHistoricoParams) (PilotoHistorico, error) {
	row := q.db.QueryRowContext(ctx, crearPilotoHistorico,
		arg.IDPiloto,
		arg.Nombre,
		arg.Pais,
		arg.FechaNacimiento,
		arg.Column5,
	)
	var i PilotoHistorico
	err := row.Scan(
		&i.IDPiloto,
		&i.Nombre,
		&i.Pais,
		&i.FechaNacimiento,
		&i.TitulosGanados,
	)
	return i, err
}

const crearPilotoTemporada = `-- name: CrearPilotoTemporada :one

INSERT INTO piloto (
    id_piloto,
    id_escuderia,
    puntos_temporada
) VALUES (
    $1,
    $2,
    COALESCE($3, 0)
)
RETURNING id_piloto, id_escuderia, puntos_temporada
`

type CrearPilotoTemporadaParams struct {
	IDPiloto    int32          `json:"id_piloto"`
	IDEscuderia sql.NullString `json:"id_escuderia"`
	Column3     interface{}    `json:"column_3"`
}

// ==========================================
// PILOTOS DE LA TEMPORADA
// ==========================================
// Inscribir a un piloto histórico en la temporada actual
func (q *Queries) CrearPilotoTemporada(ctx context.Context, arg CrearPilotoTemporadaParams) (Piloto, error) {
	row := q.db.QueryRowContext(ctx, crearPilotoTemporada, arg.IDPiloto, arg.IDEscuderia, arg.Column3)
	var i Piloto
	err := row.Scan(&i.IDPiloto, &i.IDEscuderia, &i.PuntosTemporada)
	return i, err
}

const crearUsuario = `-- name: CrearUsuario :one

INSERT INTO usuario (
    nombre_usuario,
    contrasena_hash,
    puntos_ganados
) VALUES (
    $1, $2, COALESCE($3, 0)
)
RETURNING id_usuario, nombre_usuario, puntos_ganados
`

type CrearUsuarioParams struct {
	NombreUsuario  string      `json:"nombre_usuario"`
	ContrasenaHash string      `json:"contrasena_hash"`
	Column3        interface{} `json:"column_3"`
}

type CrearUsuarioRow struct {
	IDUsuario     int32         `json:"id_usuario"`
	NombreUsuario string        `json:"nombre_usuario"`
	PuntosGanados sql.NullInt32 `json:"puntos_ganados"`
}

// ==========================================
// USUARIOS
// ==========================================
// Crear un nuevo usuario
func (q *Queries) CrearUsuario(ctx context.Context, arg CrearUsuarioParams) (CrearUsuarioRow, error) {
	row := q.db.QueryRowContext(ctx, crearUsuario, arg.NombreUsuario, arg.ContrasenaHash, arg.Column3)
	var i CrearUsuarioRow
	err := row.Scan(&i.IDUsuario, &i.NombreUsuario, &i.PuntosGanados)
	return i, err
}

const eliminarUsuario = `-- name: EliminarUsuario :exec
DELETE FROM usuario
WHERE id_usuario = $1
`

// Eliminar un usuario
func (q *Queries) EliminarUsuario(ctx context.Context, idUsuario int32) error {
	_, err := q.db.ExecContext(ctx, eliminarUsuario, idUsuario)
	return err
}

const listarApuestasPorUsuario = `-- name: ListarApuestasPorUsuario :many
SELECT
    id_apuesta,
    id_gran_premio,
    fecha_carrera,
    prediccion,
    fecha_apuesta
FROM apuesta
WHERE id_usuario = $1
ORDER BY fecha_apuesta DESC
`

type ListarApuestasPorUsuarioRow struct {
	IDApuesta    int32        `json:"id_apuesta"`
	IDGranPremio string       `json:"id_gran_premio"`
	FechaCarrera time.Time    `json:"fecha_carrera"`
	Prediccion   []int32      `json:"prediccion"`
	FechaApuesta sql.NullTime `json:"fecha_apuesta"`
}

// Listar apuestas registradas por un usuario
func (q *Queries) ListarApuestasPorUsuario(ctx context.Context, idUsuario int32) ([]ListarApuestasPorUsuarioRow, error) {
	rows, err := q.db.QueryContext(ctx, listarApuestasPorUsuario, idUsuario)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarApuestasPorUsuarioRow
	for rows.Next() {
		var i ListarApuestasPorUsuarioRow
		if err := rows.Scan(
			&i.IDApuesta,
			&i.IDGranPremio,
			&i.FechaCarrera,
			pq.Array(&i.Prediccion),
			&i.FechaApuesta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarEscuderias = `-- name: ListarEscuderias :many
SELECT
    id_escuderia,
    puntos_temporada,
    titulos_constructores,
    fecha_fundacion,
    team_principal
FROM escuderia
ORDER BY puntos_temporada DESC
`

// Mostrar todas las escuderías ordenadas por puntos
func (q *Queries) ListarEscuderias(ctx context.Context) ([]Escuderium, error) {
	rows, err := q.db.QueryContext(ctx, listarEscuderias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Escuderium
	for rows.Next() {
		var i Escuderium
		if err := rows.Scan(
			&i.IDEscuderia,
			&i.PuntosTemporada,
			&i.TitulosConstructores,
			&i.FechaFundacion,
			&i.TeamPrincipal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarGrandesPremios = `-- name: ListarGrandesPremios :many
SELECT
    gp.id_gran_premio,
    gp.pais,
    gp.longitud_km,
    gp.cantidad_vueltas,
    gp.id_ultimo_ganador,
    ph.nombre AS nombre_ultimo_ganador
FROM gran_premio gp
LEFT JOIN piloto_historico ph
    ON gp.id_ultimo_ganador = ph.id_piloto
ORDER BY gp.id_gran_premio ASC
`

type ListarGrandesPremiosRow struct {
	IDGranPremio        string         `json:"id_gran_premio"`
	Pais                string         `json:"pais"`
	LongitudKm          sql.NullString `json:"longitud_km"`
	CantidadVueltas     sql.NullInt32  `json:"cantidad_vueltas"`
	IDUltimoGanador     sql.NullInt32  `json:"id_ultimo_ganador"`
	NombreUltimoGanador sql.NullString `json:"nombre_ultimo_ganador"`
}

// Listar circuitos con la información de su último ganador
func (q *Queries) ListarGrandesPremios(ctx context.Context) ([]ListarGrandesPremiosRow, error) {
	rows, err := q.db.QueryContext(ctx, listarGrandesPremios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarGrandesPremiosRow
	for rows.Next() {
		var i ListarGrandesPremiosRow
		if err := rows.Scan(
			&i.IDGranPremio,
			&i.Pais,
			&i.LongitudKm,
			&i.CantidadVueltas,
			&i.IDUltimoGanador,
			&i.NombreUltimoGanador,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarGrandesPremiosHistoricos = `-- name: ListarGrandesPremiosHistoricos :many
SELECT
    gph.id_gran_premio,
    gph.fecha_carrera,
    gph.resultado_carrera,
    gp.pais,
    gp.longitud_km,
    gp.cantidad_vueltas
FROM gran_premio_historico gph
INNER JOIN gran_premio gp
    ON gph.id_gran_premio = gp.id_gran_premio
ORDER BY gph.fecha_carrera ASC
`

type ListarGrandesPremiosHistoricosRow struct {
	IDGranPremio     string         `json:"id_gran_premio"`
	FechaCarrera     time.Time      `json:"fecha_carrera"`
	ResultadoCarrera []int32        `json:"resultado_carrera"`
	Pais             string         `json:"pais"`
	LongitudKm       sql.NullString `json:"longitud_km"`
	CantidadVueltas  sql.NullInt32  `json:"cantidad_vueltas"`
}

// Obtener las carreras programadas unificando
// la información del circuito
func (q *Queries) ListarGrandesPremiosHistoricos(ctx context.Context) ([]ListarGrandesPremiosHistoricosRow, error) {
	rows, err := q.db.QueryContext(ctx, listarGrandesPremiosHistoricos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarGrandesPremiosHistoricosRow
	for rows.Next() {
		var i ListarGrandesPremiosHistoricosRow
		if err := rows.Scan(
			&i.IDGranPremio,
			&i.FechaCarrera,
			pq.Array(&i.ResultadoCarrera),
			&i.Pais,
			&i.LongitudKm,
			&i.CantidadVueltas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPilotos = `-- name: ListarPilotos :many
SELECT
    p.id_piloto,
    ph.nombre,
    ph.pais,
    ph.fecha_nacimiento,
    ph.titulos_ganados,
    p.id_escuderia,
    p.puntos_temporada
FROM piloto p
INNER JOIN piloto_historico ph
    ON p.id_piloto = ph.id_piloto
ORDER BY p.puntos_temporada DESC, ph.nombre ASC
`

type ListarPilotosRow struct {
	IDPiloto        int32          `json:"id_piloto"`
	Nombre          string         `json:"nombre"`
	Pais            string         `json:"pais"`
	FechaNacimiento time.Time      `json:"fecha_nacimiento"`
	TitulosGanados  sql.NullInt32  `json:"titulos_ganados"`
	IDEscuderia     sql.NullString `json:"id_escuderia"`
	PuntosTemporada sql.NullInt32  `json:"puntos_temporada"`
}

// Listar pilotos activos en la temporada
// unificando sus datos históricos
func (q *Queries) ListarPilotos(ctx context.Context) ([]ListarPilotosRow, error) {
	rows, err := q.db.QueryContext(ctx, listarPilotos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarPilotosRow
	for rows.Next() {
		var i ListarPilotosRow
		if err := rows.Scan(
			&i.IDPiloto,
			&i.Nombre,
			&i.Pais,
			&i.FechaNacimiento,
			&i.TitulosGanados,
			&i.IDEscuderia,
			&i.PuntosTemporada,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPilotosHistoricos = `-- name: ListarPilotosHistoricos :many
SELECT
    id_piloto,
    nombre,
    pais,
    fecha_nacimiento,
    titulos_ganados
FROM piloto_historico
ORDER BY titulos_ganados DESC, nombre ASC
`

// Obtener catálogo histórico general de pilotos
func (q *Queries) ListarPilotosHistoricos(ctx context.Context) ([]PilotoHistorico, error) {
	rows, err := q.db.QueryContext(ctx, listarPilotosHistoricos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PilotoHistorico
	for rows.Next() {
		var i PilotoHistorico
		if err := rows.Scan(
			&i.IDPiloto,
			&i.Nombre,
			&i.Pais,
			&i.FechaNacimiento,
			&i.TitulosGanados,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const modificarApuesta = `-- name: ModificarApuesta :one
UPDATE apuesta
SET
    prediccion = $2,
    fecha_apuesta = CURRENT_TIMESTAMP
WHERE id_apuesta = $1
RETURNING
    id_apuesta,
    id_usuario,
    id_gran_premio,
    fecha_carrera,
    prediccion,
    fecha_apuesta
`

type ModificarApuestaParams struct {
	IDApuesta  int32   `json:"id_apuesta"`
	Prediccion []int32 `json:"prediccion"`
}

// Actualizar la predicción de una apuesta
func (q *Queries) ModificarApuesta(ctx context.Context, arg ModificarApuestaParams) (Apuestum, error) {
	row := q.db.QueryRowContext(ctx, modificarApuesta, arg.IDApuesta, pq.Array(arg.Prediccion))
	var i Apuestum
	err := row.Scan(
		&i.IDApuesta,
		&i.IDUsuario,
		&i.IDGranPremio,
		&i.FechaCarrera,
		pq.Array(&i.Prediccion),
		&i.FechaApuesta,
	)
	return i, err
}

const modificarUsuario = `-- name: ModificarUsuario :one
UPDATE usuario
SET
    nombre_usuario = COALESCE($2, nombre_usuario),
    contrasena_hash = COALESCE($3, contrasena_hash),
    puntos_ganados = COALESCE($4, puntos_ganados)
WHERE id_usuario = $1
RETURNING id_usuario, nombre_usuario, puntos_ganados
`

type ModificarUsuarioParams struct {
	IDUsuario      int32         `json:"id_usuario"`
	NombreUsuario  string        `json:"nombre_usuario"`
	ContrasenaHash string        `json:"contrasena_hash"`
	PuntosGanados  sql.NullInt32 `json:"puntos_ganados"`
}

type ModificarUsuarioRow struct {
	IDUsuario     int32         `json:"id_usuario"`
	NombreUsuario string        `json:"nombre_usuario"`
	PuntosGanados sql.NullInt32 `json:"puntos_ganados"`
}

// Modificar datos de usuario
func (q *Queries) ModificarUsuario(ctx context.Context, arg ModificarUsuarioParams) (ModificarUsuarioRow, error) {
	row := q.db.QueryRowContext(ctx, modificarUsuario,
		arg.IDUsuario,
		arg.NombreUsuario,
		arg.ContrasenaHash,
		arg.PuntosGanados,
	)
	var i ModificarUsuarioRow
	err := row.Scan(&i.IDUsuario, &i.NombreUsuario, &i.PuntosGanados)
	return i, err
}

const recuperarApuesta = `-- name: RecuperarApuesta :many
SELECT
    id_apuesta,
    id_usuario,
    id_gran_premio,
    fecha_carrera,
    prediccion,
    fecha_apuesta
FROM apuesta
WHERE id_apuesta = $1
`

// Obtener apuestas por ID
func (q *Queries) RecuperarApuesta(ctx context.Context, idApuesta int32) ([]Apuestum, error) {
	rows, err := q.db.QueryContext(ctx, recuperarApuesta, idApuesta)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Apuestum
	for rows.Next() {
		var i Apuestum
		if err := rows.Scan(
			&i.IDApuesta,
			&i.IDUsuario,
			&i.IDGranPremio,
			&i.FechaCarrera,
			pq.Array(&i.Prediccion),
			&i.FechaApuesta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recuperarUsuarioPorId = `-- name: RecuperarUsuarioPorId :one
SELECT
    id_usuario,
    nombre_usuario,
    puntos_ganados
FROM usuario
WHERE id_usuario = $1
`

type RecuperarUsuarioPorIdRow struct {
	IDUsuario     int32         `json:"id_usuario"`
	NombreUsuario string        `json:"nombre_usuario"`
	PuntosGanados sql.NullInt32 `json:"puntos_ganados"`
}

// Obtener usuario por ID
func (q *Queries) RecuperarUsuarioPorId(ctx context.Context, idUsuario int32) (RecuperarUsuarioPorIdRow, error) {
	row := q.db.QueryRowContext(ctx, recuperarUsuarioPorId, idUsuario)
	var i RecuperarUsuarioPorIdRow
	err := row.Scan(&i.IDUsuario, &i.NombreUsuario, &i.PuntosGanados)
	return i, err
}

const registrarResultadoCarrera = `-- name: RegistrarResultadoCarrera :one
UPDATE gran_premio_historico
SET resultado_carrera = $3
WHERE id_gran_premio = $1
  AND fecha_carrera = $2
RETURNING id_gran_premio, fecha_carrera, resultado_carrera
`

type RegistrarResultadoCarreraParams struct {
	IDGranPremio     string    `json:"id_gran_premio"`
	FechaCarrera     time.Time `json:"fecha_carrera"`
	ResultadoCarrera []int32   `json:"resultado_carrera"`
}

// Cargar el resultado final de una carrera
func (q *Queries) RegistrarResultadoCarrera(ctx context.Context, arg RegistrarResultadoCarreraParams) (GranPremioHistorico, error) {
	row := q.db.QueryRowContext(ctx, registrarResultadoCarrera, arg.IDGranPremio, arg.FechaCarrera, pq.Array(arg.ResultadoCarrera))
	var i GranPremioHistorico
	err := row.Scan(&i.IDGranPremio, &i.FechaCarrera, pq.Array(&i.ResultadoCarrera))
	return i, err
}
