// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const borrarApuesta = `-- name: BorrarApuesta :exec
DELETE FROM apuestas
WHERE id_apuesta = $1
`

// Eliminar una apuesta por su ID
func (q *Queries) BorrarApuesta(ctx context.Context, idApuesta int32) error {
	_, err := q.db.ExecContext(ctx, borrarApuesta, idApuesta)
	return err
}

const crearApuesta = `-- name: CrearApuesta :one
INSERT INTO apuestas (
    id_usuario,
    id_gran_premio,
    prediccion
) VALUES (
    $1, $2, $3
) RETURNING id_apuesta, id_usuario, id_gran_premio, prediccion, fecha_apuesta
`

type CrearApuestaParams struct {
	IDUsuario    int32   `json:"id_usuario"`
	IDGranPremio string  `json:"id_gran_premio"`
	Prediccion   []int32 `json:"prediccion"`
}

// Crear una nueva apuesta en la base de datos
func (q *Queries) CrearApuesta(ctx context.Context, arg CrearApuestaParams) (Apuesta, error) {
	row := q.db.QueryRowContext(ctx, crearApuesta, arg.IDUsuario, arg.IDGranPremio, pq.Array(arg.Prediccion))
	var i Apuesta
	err := row.Scan(
		&i.IDApuesta,
		&i.IDUsuario,
		&i.IDGranPremio,
		pq.Array(&i.Prediccion),
		&i.FechaApuesta,
	)
	return i, err
}

const crearUsuario = `-- name: CrearUsuario :one
INSERT INTO usuarios (
    nombre_usuario,
    contrasena_hash,
    puntos_ganados
) VALUES (
    $1, $2, COALESCE($3, 0)
) RETURNING id_usuario, nombre_usuario, puntos_ganados
`

type CrearUsuarioParams struct {
	NombreUsuario  string      `json:"nombre_usuario"`
	ContrasenaHash string      `json:"contrasena_hash"`
	Column3        interface{} `json:"column_3"`
}

type CrearUsuarioRow struct {
	IDUsuario     int32         `json:"id_usuario"`
	NombreUsuario string        `json:"nombre_usuario"`
	PuntosGanados sql.NullInt32 `json:"puntos_ganados"`
}

// Crear un nuevo usuario
func (q *Queries) CrearUsuario(ctx context.Context, arg CrearUsuarioParams) (CrearUsuarioRow, error) {
	row := q.db.QueryRowContext(ctx, crearUsuario, arg.NombreUsuario, arg.ContrasenaHash, arg.Column3)
	var i CrearUsuarioRow
	err := row.Scan(&i.IDUsuario, &i.NombreUsuario, &i.PuntosGanados)
	return i, err
}

const listarApuestasPorUsuario = `-- name: ListarApuestasPorUsuario :many
SELECT 
    id_apuesta,
    id_gran_premio,
    prediccion,
    fecha_apuesta
FROM apuestas
WHERE id_usuario = $1
ORDER BY fecha_apuesta DESC
`

type ListarApuestasPorUsuarioRow struct {
	IDApuesta    int32        `json:"id_apuesta"`
	IDGranPremio string       `json:"id_gran_premio"`
	Prediccion   []int32      `json:"prediccion"`
	FechaApuesta sql.NullTime `json:"fecha_apuesta"`
}

// Listar todas las apuestas registradas por un usuario
func (q *Queries) ListarApuestasPorUsuario(ctx context.Context, idUsuario int32) ([]ListarApuestasPorUsuarioRow, error) {
	rows, err := q.db.QueryContext(ctx, listarApuestasPorUsuario, idUsuario)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarApuestasPorUsuarioRow
	for rows.Next() {
		var i ListarApuestasPorUsuarioRow
		if err := rows.Scan(
			&i.IDApuesta,
			&i.IDGranPremio,
			pq.Array(&i.Prediccion),
			&i.FechaApuesta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarEscuderias = `-- name: ListarEscuderias :many
SELECT 
    id_escuderia,
    puntos_temporada,
    titulos_constructores,
    fecha_fundacion,
    team_principal
FROM escuderias
ORDER BY puntos_temporada DESC
`

// Mostrar todas las escuderías registradas
func (q *Queries) ListarEscuderias(ctx context.Context) ([]Escuderia, error) {
	rows, err := q.db.QueryContext(ctx, listarEscuderias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Escuderia
	for rows.Next() {
		var i Escuderia
		if err := rows.Scan(
			&i.IDEscuderia,
			&i.PuntosTemporada,
			&i.TitulosConstructores,
			&i.FechaFundacion,
			&i.TeamPrincipal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarGrandesPremios = `-- name: ListarGrandesPremios :many
SELECT 
    id_gran_premio,
    pais,
    id_ultimo_ganador,
    longitud_km,
    cantidad_vueltas
FROM gran_premios
ORDER BY id_gran_premio ASC
`

// Mostrar todos los Grandes Premios registrados
func (q *Queries) ListarGrandesPremios(ctx context.Context) ([]GranPremio, error) {
	rows, err := q.db.QueryContext(ctx, listarGrandesPremios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GranPremio
	for rows.Next() {
		var i GranPremio
		if err := rows.Scan(
			&i.IDGranPremio,
			&i.Pais,
			&i.IDUltimoGanador,
			&i.LongitudKm,
			&i.CantidadVueltas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPilotos = `-- name: ListarPilotos :many
SELECT 
    id_piloto,
    nombre,
    pais,
    fecha_nacimiento,
    id_escuderia,
    titulos_ganados,
    puntos_temporada
FROM pilotos
ORDER BY puntos_temporada DESC, nombre ASC
`

// Mostrar todos los pilotos registrados
func (q *Queries) ListarPilotos(ctx context.Context) ([]Piloto, error) {
	rows, err := q.db.QueryContext(ctx, listarPilotos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Piloto
	for rows.Next() {
		var i Piloto
		if err := rows.Scan(
			&i.IDPiloto,
			&i.Nombre,
			&i.Pais,
			&i.FechaNacimiento,
			&i.IDEscuderia,
			&i.TitulosGanados,
			&i.PuntosTemporada,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const modificarApuesta = `-- name: ModificarApuesta :exec
UPDATE apuestas
SET 
    prediccion = $2,
    fecha_apuesta = CURRENT_TIMESTAMP
WHERE id_apuesta = $1
RETURNING id_apuesta, id_usuario, id_gran_premio, prediccion, fecha_apuesta
`

type ModificarApuestaParams struct {
	IDApuesta  int32   `json:"id_apuesta"`
	Prediccion []int32 `json:"prediccion"`
}

// Actualizar la predicción de una apuesta por su ID
func (q *Queries) ModificarApuesta(ctx context.Context, arg ModificarApuestaParams) error {
	_, err := q.db.ExecContext(ctx, modificarApuesta, arg.IDApuesta, pq.Array(arg.Prediccion))
	return err
}

const modificarUsuario = `-- name: ModificarUsuario :exec
UPDATE usuarios
SET 
    nombre_usuario = COALESCE($2, nombre_usuario),
    contrasena_hash = COALESCE($3, contrasena_hash),
    puntos_ganados = COALESCE($4, puntos_ganados)
WHERE id_usuario = $1
RETURNING id_usuario, nombre_usuario, puntos_ganados
`

type ModificarUsuarioParams struct {
	IDUsuario      int32         `json:"id_usuario"`
	NombreUsuario  string        `json:"nombre_usuario"`
	ContrasenaHash string        `json:"contrasena_hash"`
	PuntosGanados  sql.NullInt32 `json:"puntos_ganados"`
}

// Modificar un usuario existente
func (q *Queries) ModificarUsuario(ctx context.Context, arg ModificarUsuarioParams) error {
	_, err := q.db.ExecContext(ctx, modificarUsuario,
		arg.IDUsuario,
		arg.NombreUsuario,
		arg.ContrasenaHash,
		arg.PuntosGanados,
	)
	return err
}

const recuperarApuesta = `-- name: RecuperarApuesta :one
SELECT 
    id_apuesta,
    id_usuario,
    id_gran_premio,
    prediccion,
    fecha_apuesta
FROM apuestas
WHERE id_apuesta = $1
`

// Obtener una apuesta por su ID
func (q *Queries) RecuperarApuesta(ctx context.Context, idApuesta int32) (Apuesta, error) {
	row := q.db.QueryRowContext(ctx, recuperarApuesta, idApuesta)
	var i Apuesta
	err := row.Scan(
		&i.IDApuesta,
		&i.IDUsuario,
		&i.IDGranPremio,
		pq.Array(&i.Prediccion),
		&i.FechaApuesta,
	)
	return i, err
}
